export { default as Header } from "./Header";
export { default as About } from "./About";
export { default as Service } from "./Service";
export { default as Featured } from "./Featured";
export { default as Projects } from "./Projects";
export { default as Testimonials } from "./Testimonials";
export { default as Footer } from "./Footer";
export { default as Skills } from "./Skills";
export { default as Brand } from "./Brand";
